//////////////////////////////////////////////////////
// SigmaPlayer Project.
// File auto-generated from MMSL language reference.
//////////////////////////////////////////////////////

static const struct SCRIPT_VAR
{
    MmslVariableCallback Get, Set;
    int ID;
} script_vars[] = 
{
    {  on_kernel_get, on_kernel_set,	SCRIPT_VAR_KERNEL_POWER },
    {  on_kernel_get, on_kernel_set,	SCRIPT_VAR_KERNEL_FREQUENCY },
    {  on_kernel_get, on_kernel_set,	SCRIPT_VAR_KERNEL_CHIP },
    {  on_kernel_get, on_kernel_set,	SCRIPT_VAR_KERNEL_FREE_MEMORY },
    {  on_kernel_get, on_kernel_set,	SCRIPT_VAR_KERNEL_FLASH_MEMORY },
    {  on_kernel_get, on_kernel_set,	SCRIPT_VAR_KERNEL_PRINT },
    {  on_kernel_get, on_kernel_set,	SCRIPT_VAR_KERNEL_FIRMWARE_VERSION },
    {  on_kernel_get, on_kernel_set,	SCRIPT_VAR_KERNEL_MMSL_VERSION },
    {  on_kernel_get, on_kernel_set,	SCRIPT_VAR_KERNEL_MMSL_ERRORS },
    {  on_kernel_get, on_kernel_set,	SCRIPT_VAR_KERNEL_RUN },
    {  on_kernel_get, on_kernel_set,	SCRIPT_VAR_KERNEL_RANDOM },

    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_SWITCH },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_UPDATE },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_TVSTANDARD },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_TVOUT },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_LEFT },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_TOP },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_RIGHT },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_BOTTOM },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_PALETTE },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_PALIDX },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_PALALPHA },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_PALCOLOR },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_FONT },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_COLOR },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_BACKCOLOR },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_TRCOLOR },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_HALIGN },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_VALIGN },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_BACK },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_BACK_LEFT },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_BACK_TOP },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_BACK_RIGHT },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_BACK_BOTTOM },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_PRELOAD },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_HZOOM },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_VZOOM },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_HSCROLL },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_VSCROLL },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_ROTATE },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_BRIGHTNESS },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_CONTRAST },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_SATURATION },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_FULLSCREEN },

    {  on_pad_get, on_pad_set,	SCRIPT_VAR_PAD_KEY },
    {  on_pad_get, on_pad_set,	SCRIPT_VAR_PAD_DISPLAY },
    {  on_pad_get, on_pad_set,	SCRIPT_VAR_PAD_SET },
    {  on_pad_get, on_pad_set,	SCRIPT_VAR_PAD_CLEAR },

    {  on_drive_get, on_drive_set,	SCRIPT_VAR_DRIVE_MEDIATYPE },
    {  on_drive_get, on_drive_set,	SCRIPT_VAR_DRIVE_TRAY },

    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_CHARSET },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_FOLDER },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_TARGET },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_FILTER },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_MASK1 },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_MASK2 },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_MASK3 },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_MASK4 },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_MASK5 },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_PATH },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_FILENAME },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_EXTENSION },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_DRIVE_LETTER },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_TYPE },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_MASKINDEX },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_FILESIZE },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_FILETIME },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_COUNT },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_SORT },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_POSITION },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_COMMAND },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_FIND },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_COPIED },

    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_SOURCE },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_PLAYING },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_SAVED },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_COMMAND },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_SELECT },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_REPEAT },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_SPEED },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_MENU },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_LANGUAGE_MENU },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_LANGUAGE_AUDIO },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_LANGUAGE_SUBTITLE },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_SUBTITLE_CHARSET },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_SUBTITLE_WRAP },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_SUBTITLE },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_ANGLE },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_VOLUME },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_BALANCE },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_AUDIO_OFFSET },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_TIME },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_TITLE },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_CHAPTER },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_NAME },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_ARTIST },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_AUDIO_INFO },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_VIDEO_INFO },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_AUDIO_STREAM },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_SUBTITLE_STREAM },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_LENGTH },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_NUM_TITLES },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_NUM_CHAPTERS },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_WIDTH },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_HEIGHT },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_FRAME_RATE },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_COLOR_SPACE },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_DEBUG },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_ERROR },

    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_COMMAND },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_AUDIOOUT },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_TVTYPE },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_TVSTANDARD },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_TVOUT },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_DVI },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_HQ_JPEG },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_HDD_SPEED },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_DVD_PARENTAL },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_DVD_MV },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_DVD_LANG_MENU },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_DVD_LANG_AUDIO },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_DVD_LANG_SPU },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_VOLUME },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_BALANCE },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_BRIGHTNESS },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_CONTRAST },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_SATURATION },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER1 },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER2 },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER3 },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER4 },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER5 },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER6 },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER7 },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER8 },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER9 },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER10 },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER11 },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER12 },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER13 },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER14 },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER15 },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER16 },

    {  on_flash_get, on_flash_set,	SCRIPT_VAR_FLASH_FILE },
    {  on_flash_get, on_flash_set,	SCRIPT_VAR_FLASH_ADDRESS },
    {  on_flash_get, on_flash_set,	SCRIPT_VAR_FLASH_PROGRESS },
    { NULL, NULL, -1, }
};

