//////////////////////////////////////////////////////
// SigmaPlayer Project.
// File auto-generated from MMSL language reference.
//////////////////////////////////////////////////////

static const struct SCRIPT_VAR
{
    MmslVariableCallback Get, Set;
    int ID;
    const char *name;
} script_vars[] = 
{
    {  on_kernel_get, on_kernel_set,	SCRIPT_VAR_KERNEL_POWER,		"kernel.power" },
    {  on_kernel_get, on_kernel_set,	SCRIPT_VAR_KERNEL_FREQUENCY,		"kernel.frequency" },
    {  on_kernel_get, on_kernel_set,	SCRIPT_VAR_KERNEL_CHIP,		"kernel.chip" },
    {  on_kernel_get, on_kernel_set,	SCRIPT_VAR_KERNEL_FREE_MEMORY,		"kernel.free_memory" },
    {  on_kernel_get, on_kernel_set,	SCRIPT_VAR_KERNEL_FLASH_MEMORY,		"kernel.flash_memory" },
    {  on_kernel_get, on_kernel_set,	SCRIPT_VAR_KERNEL_PRINT,		"kernel.print" },
    {  on_kernel_get, on_kernel_set,	SCRIPT_VAR_KERNEL_FIRMWARE_VERSION,		"kernel.firmware_version" },
    {  on_kernel_get, on_kernel_set,	SCRIPT_VAR_KERNEL_MMSL_VERSION,		"kernel.mmsl_version" },
    {  on_kernel_get, on_kernel_set,	SCRIPT_VAR_KERNEL_MMSL_ERRORS,		"kernel.mmsl_errors" },
    {  on_kernel_get, on_kernel_set,	SCRIPT_VAR_KERNEL_RUN,		"kernel.run" },
    {  on_kernel_get, on_kernel_set,	SCRIPT_VAR_KERNEL_RANDOM,		"kernel.random" },

    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_SWITCH,		"screen.switch" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_UPDATE,		"screen.update" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_TVSTANDARD,		"screen.tvstandard" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_TVOUT,		"screen.tvout" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_LEFT,		"screen.left" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_TOP,		"screen.top" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_RIGHT,		"screen.right" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_BOTTOM,		"screen.bottom" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_PALETTE,		"screen.palette" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_PALIDX,		"screen.palidx" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_PALALPHA,		"screen.palalpha" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_PALCOLOR,		"screen.palcolor" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_FONT,		"screen.font" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_COLOR,		"screen.color" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_BACKCOLOR,		"screen.backcolor" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_TRCOLOR,		"screen.trcolor" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_HALIGN,		"screen.halign" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_VALIGN,		"screen.valign" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_BACK,		"screen.back" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_BACK_LEFT,		"screen.back_left" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_BACK_TOP,		"screen.back_top" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_BACK_RIGHT,		"screen.back_right" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_BACK_BOTTOM,		"screen.back_bottom" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_PRELOAD,		"screen.preload" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_HZOOM,		"screen.hzoom" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_VZOOM,		"screen.vzoom" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_HSCROLL,		"screen.hscroll" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_VSCROLL,		"screen.vscroll" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_ROTATE,		"screen.rotate" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_BRIGHTNESS,		"screen.brightness" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_CONTRAST,		"screen.contrast" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_SATURATION,		"screen.saturation" },
    {  on_screen_get, on_screen_set,	SCRIPT_VAR_SCREEN_FULLSCREEN,		"screen.fullscreen" },

    {  on_pad_get, on_pad_set,	SCRIPT_VAR_PAD_KEY,		"pad.key" },
    {  on_pad_get, on_pad_set,	SCRIPT_VAR_PAD_DISPLAY,		"pad.display" },
    {  on_pad_get, on_pad_set,	SCRIPT_VAR_PAD_SET,		"pad.set" },
    {  on_pad_get, on_pad_set,	SCRIPT_VAR_PAD_CLEAR,		"pad.clear" },

    {  on_drive_get, on_drive_set,	SCRIPT_VAR_DRIVE_MEDIATYPE,		"drive.mediatype" },
    {  on_drive_get, on_drive_set,	SCRIPT_VAR_DRIVE_TRAY,		"drive.tray" },

    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_CHARSET,		"explorer.charset" },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_FOLDER,		"explorer.folder" },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_TARGET,		"explorer.target" },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_FILTER,		"explorer.filter" },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_MASK1,		"explorer.mask1" },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_MASK2,		"explorer.mask2" },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_MASK3,		"explorer.mask3" },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_MASK4,		"explorer.mask4" },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_MASK5,		"explorer.mask5" },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_PATH,		"explorer.path" },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_FILENAME,		"explorer.filename" },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_EXTENSION,		"explorer.extension" },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_DRIVE_LETTER,		"explorer.drive_letter" },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_TYPE,		"explorer.type" },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_MASKINDEX,		"explorer.maskindex" },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_FILESIZE,		"explorer.filesize" },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_FILETIME,		"explorer.filetime" },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_COUNT,		"explorer.count" },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_SORT,		"explorer.sort" },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_POSITION,		"explorer.position" },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_COMMAND,		"explorer.command" },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_FIND,		"explorer.find" },
    {  on_explorer_get, on_explorer_set,	SCRIPT_VAR_EXPLORER_COPIED,		"explorer.copied" },

    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_SOURCE,		"player.source" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_PLAYING,		"player.playing" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_SAVED,		"player.saved" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_COMMAND,		"player.command" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_SELECT,		"player.select" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_REPEAT,		"player.repeat" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_SPEED,		"player.speed" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_MENU,		"player.menu" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_LANGUAGE_MENU,		"player.language_menu" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_LANGUAGE_AUDIO,		"player.language_audio" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_LANGUAGE_SUBTITLE,		"player.language_subtitle" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_SUBTITLE_CHARSET,		"player.subtitle_charset" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_SUBTITLE_WRAP,		"player.subtitle_wrap" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_SUBTITLE,		"player.subtitle" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_ANGLE,		"player.angle" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_VOLUME,		"player.volume" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_BALANCE,		"player.balance" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_AUDIO_OFFSET,		"player.audio_offset" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_TIME,		"player.time" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_TITLE,		"player.title" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_CHAPTER,		"player.chapter" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_NAME,		"player.name" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_ARTIST,		"player.artist" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_AUDIO_INFO,		"player.audio_info" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_VIDEO_INFO,		"player.video_info" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_AUDIO_STREAM,		"player.audio_stream" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_SUBTITLE_STREAM,		"player.subtitle_stream" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_LENGTH,		"player.length" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_NUM_TITLES,		"player.num_titles" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_NUM_CHAPTERS,		"player.num_chapters" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_WIDTH,		"player.width" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_HEIGHT,		"player.height" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_FRAME_RATE,		"player.frame_rate" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_COLOR_SPACE,		"player.color_space" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_DEBUG,		"player.debug" },
    {  on_player_get, on_player_set,	SCRIPT_VAR_PLAYER_ERROR,		"player.error" },

    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_COMMAND,		"settings.command" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_AUDIOOUT,		"settings.audioout" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_TVTYPE,		"settings.tvtype" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_TVSTANDARD,		"settings.tvstandard" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_TVOUT,		"settings.tvout" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_DVI,		"settings.dvi" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_HQ_JPEG,		"settings.hq_jpeg" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_HDD_SPEED,		"settings.hdd_speed" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_DVD_PARENTAL,		"settings.dvd_parental" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_DVD_MV,		"settings.dvd_mv" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_DVD_LANG_MENU,		"settings.dvd_lang_menu" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_DVD_LANG_AUDIO,		"settings.dvd_lang_audio" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_DVD_LANG_SPU,		"settings.dvd_lang_spu" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_VOLUME,		"settings.volume" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_BALANCE,		"settings.balance" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_BRIGHTNESS,		"settings.brightness" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_CONTRAST,		"settings.contrast" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_SATURATION,		"settings.saturation" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER1,		"settings.user1" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER2,		"settings.user2" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER3,		"settings.user3" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER4,		"settings.user4" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER5,		"settings.user5" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER6,		"settings.user6" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER7,		"settings.user7" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER8,		"settings.user8" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER9,		"settings.user9" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER10,		"settings.user10" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER11,		"settings.user11" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER12,		"settings.user12" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER13,		"settings.user13" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER14,		"settings.user14" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER15,		"settings.user15" },
    {  on_settings_get, on_settings_set,	SCRIPT_VAR_SETTINGS_USER16,		"settings.user16" },

    {  on_flash_get, on_flash_set,	SCRIPT_VAR_FLASH_FILE,		"flash.file" },
    {  on_flash_get, on_flash_set,	SCRIPT_VAR_FLASH_ADDRESS,		"flash.address" },
    {  on_flash_get, on_flash_set,	SCRIPT_VAR_FLASH_PROGRESS,		"flash.progress" },
    { NULL, NULL, -1, NULL }
};

